import{_ as u}from"./DGQDFDqB.js";import{_ as m}from"./XeBM0mME.js";import{_ as f}from"./Wh5z6A57.js";import{_ as x}from"./D3PCs1Vf.js";import{u as h}from"./JUrRgig7.js";import{g as i,j as v,n as g,s as y,w as e,o as k,a as s,b as o,v as n,a0 as I,t as M,d as w,_ as L}from"./CFOLWpXS.js";import"./DnPRtPRg.js";/**
 * @license lucide-vue-next v0.474.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const S=i("HeadphonesIcon",[["path",{d:"M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3",key:"1xhozi"}]]);/**
 * @license lucide-vue-next v0.474.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const b=i("MessageCircleIcon",[["path",{d:"M7.9 20A9 9 0 1 0 4 16.1L2 22Z",key:"vv11sd"}]]),z={class:"support-page"},B={class:"phone-row"},C={class:"phone-info"},N={class:"phone-number",dir:"ltr"},$=v({__name:"support",setup(q){const a=h();g(()=>a.fetchInitialData());function l(){const r=a.supportPhone||"02191000000";window.location.href=`tel:${r}`}return(r,t)=>{const p=u,c=m,_=f,d=x;return k(),y(d,{title:"پشتیبانی"},{default:e(()=>[s("div",z,[o(p,{padding:"28px",class:"support-hero"},{default:e(()=>[o(n(S),{size:48,class:"text-primary"}),t[0]||(t[0]=s("h2",null,"پشتیبانی شهریار",-1)),t[1]||(t[1]=s("p",{class:"text-muted"},"تیم پشتیبانی ما آماده پاسخگویی به سوالات شماست",-1))]),_:1}),o(p,{padding:"20px",class:"phone-card"},{default:e(()=>[s("div",B,[o(n(I),{size:22,class:"text-primary"}),s("div",C,[t[2]||(t[2]=s("span",{class:"phone-label"},"شماره تماس پشتیبانی",-1)),s("span",N,M(n(a).supportPhone||"021-91000000"),1)])]),o(c,{"button-text":"تماس با پشتیبانی","on-tap":l})]),_:1}),o(p,{padding:"20px",class:"request-card"},{default:e(()=>[o(n(b),{size:22,class:"text-primary"}),t[4]||(t[4]=s("div",null,[s("h3",null,"ارسال درخواست"),s("p",{class:"text-muted"},"فرم درخواست پشتیبانی را پر کنید")],-1)),o(_,{to:"/send-request",class:"request-link"},{default:e(()=>[...t[3]||(t[3]=[w("ارسال درخواست ←",-1)])]),_:1})]),_:1})])]),_:1})}}}),G=L($,[["__scopeId","data-v-8f45737e"]]);export{G as default};
