import{_ as L}from"./D8la2iwj.js";import{_ as F}from"./EB4G7-hs.js";import{g as b,j as I,a1 as T,k as E,s as h,w as i,v as e,o as l,a as s,t as o,b as c,c as _,M as m,R as y,U as d,T as k,Q as G,aG as $,S as A,aF as N,C as u,_ as P}from"./CyhIoVF8.js";import"./DMgLLmez.js";/**
 * @license lucide-vue-next v0.474.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const V=b("GlobeIcon",[["circle",{cx:"12",cy:"12",r:"10",key:"1mglay"}],["path",{d:"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20",key:"13o1zl"}],["path",{d:"M2 12h20",key:"9i4pu4"}]]);/**
 * @license lucide-vue-next v0.474.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const R=b("PaletteIcon",[["circle",{cx:"13.5",cy:"6.5",r:".5",fill:"currentColor",key:"1okk4w"}],["circle",{cx:"17.5",cy:"10.5",r:".5",fill:"currentColor",key:"f64h9f"}],["circle",{cx:"8.5",cy:"7.5",r:".5",fill:"currentColor",key:"fotxhn"}],["circle",{cx:"6.5",cy:"12.5",r:".5",fill:"currentColor",key:"qy21gx"}],["path",{d:"M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z",key:"12rzf8"}]]),U={class:"settings-page"},j={class:"section-label"},q={class:"block-head"},O={class:"theme-grid"},Q=["onClick"],Y={class:"swatch-colors"},H={class:"swatch-label"},J={class:"toggle-row"},K={class:"block-head"},W={class:"section-label"},X={class:"block-head"},Z={class:"lang-chips"},ee=["onClick"],se={class:"version-box"},te=I({__name:"settings",setup(ae){const n=T(),{locale:f,changeLanguage:v,t,tNamed:x}=E(),C=N(),w=u(()=>[{type:"purpleBlue",label:t("theme_shahryar"),colors:["#62358A","#2DAFE6"]},{type:"greenYellow",label:t("theme_spring"),colors:["#50CC61","#DEDB06"]},{type:"redOrange",label:t("theme_autumn"),colors:["#E53935","#FFA726"]},{type:"tealPink",label:t("theme_summer"),colors:["#00897B","#D81B60"]}]),D=u(()=>[{code:"fa",label:t("language_fa")},{code:"en",label:t("language_en")},{code:"ar",label:t("language_ar")}]),M=u(()=>f.value.split("_")[0]??"fa");async function z(g){await v(g)}return(g,r)=>{const p=L,B=F;return l(),h(B,{title:e(t)("settings")},{default:i(()=>[s("div",U,[s("p",j,o(e(t)("appearance")),1),c(p,{padding:"16px",class:"settings-block"},{default:i(()=>[s("div",q,[c(e(R),{size:20,class:"text-primary"}),s("span",null,o(e(t)("color_palette")),1)]),s("div",O,[(l(!0),_(m,null,y(e(w),a=>(l(),_("button",{key:a.type,class:d(["theme-swatch",{active:e(n).themeType===a.type}]),onClick:S=>e(n).setThemeType(a.type)},[s("div",Y,[s("span",{style:k({background:a.colors[0]})},null,4),s("span",{style:k({background:a.colors[1]})},null,4)]),s("span",H,o(a.label),1)],10,Q))),128))])]),_:1}),c(p,{padding:"16px",class:"settings-block"},{default:i(()=>[s("div",J,[s("div",K,[(l(),h(G(e(n).isDarkMode?e($):e(A)),{size:20,class:"text-primary"})),s("span",null,o(e(t)("dark_mode")),1)]),s("button",{class:d(["toggle-switch",{on:e(n).isDarkMode}]),onClick:r[0]||(r[0]=a=>e(n).toggleDarkMode())},[...r[1]||(r[1]=[s("span",{class:"toggle-knob"},null,-1)])],2)])]),_:1}),s("p",W,o(e(t)("language_section")),1),c(p,{padding:"16px",class:"settings-block"},{default:i(()=>[s("div",X,[c(e(V),{size:20,class:"text-primary"}),s("span",null,o(e(t)("app_language")),1)]),s("div",Z,[(l(!0),_(m,null,y(e(D),a=>(l(),_("button",{key:a.code,class:d(["lang-chip",{active:e(M)===a.code}]),onClick:S=>z(a.code)},o(a.label),11,ee))),128))])]),_:1}),s("div",se,[s("span",null,o(e(x)("version_label",{version:String(e(C).public.appVersion)})),1)])])]),_:1},8,["title"])}}}),re=P(te,[["__scopeId","data-v-57816417"]]);export{re as default};
