import{_ as z}from"./DGQDFDqB.js";import{_ as B}from"./D3PCs1Vf.js";import{g as m,j as L,S,k as I,s as u,w as n,o as c,a as e,b as a,v as o,c as _,I as g,J as y,N as r,L as k,t as d,M as E,am as F,an as T,al as $,C as A,_ as G}from"./CFOLWpXS.js";import"./DnPRtPRg.js";/**
 * @license lucide-vue-next v0.474.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const N=m("GlobeIcon",[["circle",{cx:"12",cy:"12",r:"10",key:"1mglay"}],["path",{d:"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20",key:"13o1zl"}],["path",{d:"M2 12h20",key:"9i4pu4"}]]);/**
 * @license lucide-vue-next v0.474.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const P=m("PaletteIcon",[["circle",{cx:"13.5",cy:"6.5",r:".5",fill:"currentColor",key:"1okk4w"}],["circle",{cx:"17.5",cy:"10.5",r:".5",fill:"currentColor",key:"f64h9f"}],["circle",{cx:"8.5",cy:"7.5",r:".5",fill:"currentColor",key:"fotxhn"}],["circle",{cx:"6.5",cy:"12.5",r:".5",fill:"currentColor",key:"qy21gx"}],["path",{d:"M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z",key:"12rzf8"}]]),V={class:"settings-page"},j={class:"block-head"},q={class:"theme-grid"},J=["onClick"],O={class:"swatch-colors"},R={class:"swatch-label"},U={class:"toggle-row"},Y={class:"block-head"},H={class:"block-head"},K={class:"lang-chips"},Q=["onClick"],W={class:"version-box"},X=L({__name:"settings",setup(Z){const l=S(),{locale:b,changeLanguage:f}=I(),h=$(),v=[{type:"purpleBlue",label:"بنفش-آبی",colors:["#62358A","#2DAFE6"]},{type:"greenYellow",label:"سبز-زرد",colors:["#50CC61","#DEDB06"]},{type:"redOrange",label:"قرمز-نارنجی",colors:["#E53935","#FFA726"]},{type:"tealPink",label:"فیروزه‌ای-صورتی",colors:["#00897B","#D81B60"]}],x=[{code:"fa",label:"فارسی"},{code:"en",label:"English"},{code:"ar",label:"العربية"}],C=A(()=>b.value.split("_")[0]??"fa");async function w(p){await f(p)}return(p,s)=>{const i=z,D=B;return c(),u(D,{title:"تنظیمات"},{default:n(()=>[e("div",V,[s[5]||(s[5]=e("p",{class:"section-label"},"ظاهر",-1)),a(i,{padding:"16px",class:"settings-block"},{default:n(()=>[e("div",j,[a(o(P),{size:20,class:"text-primary"}),s[1]||(s[1]=e("span",null,"پالت رنگی",-1))]),e("div",q,[(c(),_(g,null,y(v,t=>e("button",{key:t.type,class:r(["theme-swatch",{active:o(l).themeType===t.type}]),onClick:M=>o(l).setThemeType(t.type)},[e("div",O,[e("span",{style:k({background:t.colors[0]})},null,4),e("span",{style:k({background:t.colors[1]})},null,4)]),e("span",R,d(t.label),1)],10,J)),64))])]),_:1}),a(i,{padding:"16px",class:"settings-block"},{default:n(()=>[e("div",U,[e("div",Y,[(c(),u(E(o(l).isDarkMode?o(F):o(T)),{size:20,class:"text-primary"})),s[2]||(s[2]=e("span",null,"حالت تاریک",-1))]),e("button",{class:r(["toggle-switch",{on:o(l).isDarkMode}]),onClick:s[0]||(s[0]=t=>o(l).toggleDarkMode())},[...s[3]||(s[3]=[e("span",{class:"toggle-knob"},null,-1)])],2)])]),_:1}),s[6]||(s[6]=e("p",{class:"section-label"},"زبان",-1)),a(i,{padding:"16px",class:"settings-block"},{default:n(()=>[e("div",H,[a(o(N),{size:20,class:"text-primary"}),s[4]||(s[4]=e("span",null,"زبان برنامه",-1))]),e("div",K,[(c(),_(g,null,y(x,t=>e("button",{key:t.code,class:r(["lang-chip",{active:o(C)===t.code}]),onClick:M=>w(t.code)},d(t.label),11,Q)),64))])]),_:1}),e("div",W,[e("span",null,"ورژن "+d(o(h).public.appVersion),1)])])]),_:1})}}}),le=G(X,[["__scopeId","data-v-f85f148d"]]);export{le as default};
